BEGIN;
--
-- Create model Accounts
--
CREATE TABLE "accounting_accounts" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "code" varchar(6) NOT NULL UNIQUE, "name" varchar(200) NOT NULL, "code_class" integer NOT NULL, "type" varchar NOT NULL);
CREATE INDEX "accounting_accounts_code_b7aca565_like" ON "accounting_accounts" ("code" varchar_pattern_ops);
COMMIT;