# Generated by Django 6.0 on 2025-12-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('code_class', models.IntegerField(editable=False)),
                ('type', models.CharField(editable=False, max_length=1)),
            ],
        ),
    ]
