# Generated by Django 6.0 on 2025-12-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='code',
            field=models.IntegerField(max_length=6, unique=True),
        ),
    ]
