# Generated by Django 6.0 on 2026-01-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_customers_suppliers_alter_accounts_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='uptaded_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='suppliers',
            old_name='uptaded_at',
            new_name='updated_at',
        ),
    ]
