# Generated by Django 6.0 on 2026-01-10 18:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_rename_uptaded_at_customers_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='customers',
            name='account_code',
            field=models.CharField(default='A', editable=False, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers',
            name='account_code',
            field=models.CharField(default='B', editable=False, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.CreateModel(
            name='AccountsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.accounts')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.customers')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_credit', models.CharField(choices=[('D', 'D'), ('C', 'C')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountslink')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.transactionheader')),
            ],
        ),
    ]
