# Generated by Django 6.0 on 2026-01-10 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_transactionheader_customers_account_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountslink',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accounts'),
        ),
        migrations.AlterField(
            model_name='accountslink',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.customers'),
        ),
        migrations.AlterField(
            model_name='accountslink',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.suppliers'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='account_code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='account_code',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
