# Generated by Django 6.0 on 2026-01-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_accountslink_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountslink',
            options={'ordering': ['sorting_account', 'id']},
        ),
        migrations.AddField(
            model_name='accountslink',
            name='sorting_account',
            field=models.CharField(default='X', editable=False, max_length=6),
            preserve_default=False,
        ),
    ]
