# Generated by Django 6.0 on 2026-01-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_accountslink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountslink',
            name='sorting_account',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
