# Generated by Django 6.0 on 2026-01-11 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20260111_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountslink',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accounts', unique=True),
        ),
        migrations.AlterField(
            model_name='accountslink',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.customers', unique=True),
        ),
        migrations.AlterField(
            model_name='accountslink',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.suppliers', unique=True),
        ),
    ]
