# Generated by Django 6.0 on 2026-01-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_alter_accountslink_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionheader',
            name='date',
            field=models.DateField(),
        ),
    ]
