# Generated by Django 6.0 on 2026-01-12 02:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_alter_transactionheader_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionline',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
