# Generated by Django 6.0 on 2026-01-12 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_transactionline_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountslink',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accounts'),
        ),
        migrations.AlterField(
            model_name='accountslink',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.customers'),
        ),
        migrations.AlterField(
            model_name='accountslink',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.suppliers'),
        ),
    ]
